//! Bead 3zb slice B1b: the Env <-> Images COMPOSITION layer.
//!
//! A sibling of `js_env`, deliberately: `js_env` owns generic host primitives
//! and must never import or name a `lagrange-images` module, while this layer
//! exists precisely to bind the two. The directory boundary is the ownership
//! statement, and the structural guard checks it.
//!
//! The composition itself is JavaScript (`crypto-bootstrap.js`) rather than a
//! Rust string literal, so that B2 and B3 reuse the SAME source verbatim instead
//! of re-deriving it, and so it is reviewable as the module it is.

pub mod portable_artifact;

/// The guest bootstrap that adapts the generic host crypto primitives to the
/// `lagrange-images` crypto-provider contract and installs them through the
/// public `setDefaultCryptoProvider` seam.
pub const CRYPTO_BOOTSTRAP_JS: &str = include_str!("crypto-bootstrap.js");

/// The module specifier the bootstrap is loaded under. Bare and canonical so it
/// is loader-agnostic: the artifact loader resolves this exact host overlay
/// without exposing a filesystem or package-resolution fallback.
pub const CRYPTO_BOOTSTRAP_SPECIFIER: &str = "host/crypto-bootstrap";

/// Canonical `lagrange-images-portable-runtime/v1` material embedded verbatim.
///
/// Generated by the Images-owned producer at [`PORTABLE_RUNTIME_SOURCE_REVISION`]:
///
/// ```text
/// node scripts/build-portable-runtime-artifact.mjs \
///   > lagrange-images-portable-runtime.v1.json
/// ```
///
/// The producer is deliberately NOT run by this crate or by CI. A version bump
/// is a reviewed supply-chain update: regenerate from the exact revision, prove
/// the producer's `--identity` equals the raw file SHA-256, then update the
/// bytes, identity, provenance and pinned CI checkout together.
pub const PORTABLE_RUNTIME_ARTIFACT_BYTES: &[u8] =
    include_bytes!("lagrange-images-portable-runtime.v1.json");

/// Images-owned artifact contract selected by this consumer.
pub const PORTABLE_RUNTIME_ARTIFACT_FORMAT: &str = "lagrange-images-portable-runtime/v1";

/// The real portable composition root inside the artifact.
pub const PORTABLE_RUNTIME_ARTIFACT_ENTRY: &str = "src/portable-runtime.js";

/// The Images revision the artifact was produced from. It is NOT part of the
/// canonical artifact material (which carries no provenance), but it IS the
/// AUTHORITATIVE statement of which Images revision this repository consumes:
/// the bytes + identity above are regenerated FROM it by the documented
/// procedure (a convention a bump follows; not an executable derivation — see
/// Bead on making the artifact<->revision link executable), and the CI sibling
/// checkout for the JS
/// real-runtime integration tests (`.github/workflows/ci.yml`) must name the
/// same commit — the two lanes consume different Images entries (this artifact's
/// `src/portable-runtime.js`; the sibling's `src/runtime.js`) at ONE revision.
/// `tests/portable_images_artifact.rs` asserts the agreement.
pub const PORTABLE_RUNTIME_SOURCE_REVISION: &str =
    "c0f2346e559529fc810d9d94e7e0bec84bf12f54";

/// Images-published identity over the exact canonical material bytes above.
pub const PORTABLE_RUNTIME_CONTENT_IDENTITY: &str =
    "sha256:5f2d80b421e7d63074d77419ca269818aa409142f6469e351c3b7f898e5409b3";
