//! Native Linux host — ADR 0013 / Bead hqt L1 falsification spike.
//!
//! Runs the EXACT checked-in GLB renderer Component core binary
//! (`test/browser/components/glb/glb.component.wasm`, hash-pinned) under
//! Wasmtime with native `wasi:webgpu` + `wasi-gfx:surface` host imports and the
//! Lagrange `lagrange:assets/provider` import — with NO jco, NO JS, NO browser,
//! NO DOM, and NO winit. This proves the ADR 0013 portability contract: the
//! portable artifact is the Component core binary + host-provided WIT imports,
//! not the browser jco glue.
//!
//! Architecture (Option C — headless offscreen):
//!   - REAL `wasi:webgpu` host impl (`wasi_webgpu_wasmtime::add_to_linker`).
//!   - REAL `wasi-gfx:surface/surface` host impl
//!     (`surface_wasmtime::add_surface_to_linker`) with a dummy offscreen
//!     `GfxWindow` (raw handles never used — see below).
//!   - CUSTOM `wasi-gfx:surface/surface-webgpu` host impl (this module's
//!     `OffscreenContext` via a bindgen `with` remap): instead of an on-screen
//!     wgpu surface, `get-current-texture` hands the Component a host-owned
//!     OFFSCREEN texture (`RENDER_ATTACHMENT | COPY_SRC`, Bgra8unorm —
//!     `PREFERRED_CANVAS_FORMAT` on Linux) created on the Component's own
//!     `gpu-device`, and `present()` copies that texture to a readback buffer
//!     and captures the BGRA bytes. This mirrors the browser CI
//!     `TextureRenderTarget` seam exactly: the Component cannot tell which
//!     realization it got.
//!
//! The queue-id seam: `wasi_webgpu_wasmtime`'s `Device.queue` field is
//! `pub(crate)`, so `present()` cannot name the Component device's queue for
//! the readback copy's `queue_submit` — and an encoded-but-UNSUBMITTED command
//! buffer never executes (`buffer_map_async` does NOT run pending command
//! buffers; that earlier assumption was falsified by an all-zeros readback).
//! The resolution: capture the `QueueId` in `configure` via the runtime's
//! public `HostGpuDevice::queue` host method (which pushes the device's
//! `Arc<QueueId>` into our ResourceTable), then in `present()` `queue_submit`
//! the readback copy on that queue before `buffer_map_async` + poll. No fork,
//! no Component change.

pub mod linux_adapter;
pub mod projector;
pub mod semantic_gtk;
pub mod semantic_ui;

// 3zb-A bounded Environment-side rquickjs embed (ADR 0014 fallback). Runtime
// shell only in slice 1; see js_env/mod.rs for scope, invariants, and the
// deletion criterion. NOT a Node runtime and NOT a per-language-bridge
// precedent.
pub mod images_composition;
pub mod js_env;

use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::{Arc, Mutex};

use sha2::Digest;
use surface_wasmtime::{
    GfxWindow, MainThreadSpawner, Surface, SurfaceCtx, SurfaceCtxView, SurfaceDesc,
};
use wasi_webgpu_wasmtime::reexports::{wgpu_core, wgpu_types};
use wasi_webgpu_wasmtime::{WasiWebGpuCtx, WasiWebGpuCtxView};
use wasmtime::component::{HasData, Resource};
use wasmtime::{AsContextMut, Config, Engine, Store};
use wasmtime_wasi::ResourceTable;

// ---------------------------------------------------------------------------
// bindgen: the lagrange:glb-renderer/glb-renderer world (wit/world.wit, a copy
// of renderer-component/wit/world.wit). The `with` remaps point the two shared
// imported interfaces at the runtime crates' generated modules so the Rust
// types unify, and surface-webgpu's `context` resource at OUR offscreen type.
// ---------------------------------------------------------------------------
wasmtime::component::bindgen!({
    path: "wit/",
    world: "lagrange:glb-renderer/glb-renderer",
    exports: {
        "start": async,
    },
    require_store_data_send: true,
    imports: {
        default: trappable,
    },
    with: {
        "wasi:webgpu/webgpu": wasi_webgpu_wasmtime::wasi::webgpu::webgpu,
        // `wasi_gfx` is generated by surface-wasmtime's OWN bindgen, inside its
        // private `surface` module — so the path goes through `Surface` (whose
        // type the remap needs anyway).
        "wasi-gfx:surface/surface": surface_wasmtime::surface::wasi_gfx::surface::surface,
        "wasi-gfx:surface/surface-webgpu.context": OffscreenContext,
    },
});

// The generated `wasi_gfx::surface::surface_webgpu` module (host trait impls
// for wasi-gfx:surface/surface-webgpu against OUR OffscreenContext).
use wasi_gfx::surface::surface_webgpu;

// ---------------------------------------------------------------------------
// Component artifact (READ-ONLY; the exact browser-tested binary)
// ---------------------------------------------------------------------------

const COMPONENT_RELATIVE_PATH: &str = "../../test/browser/components/glb/glb.component.wasm";
const BOX_GLB_RELATIVE_PATH: &str = "../../test/browser/box.glb";
const BOX_BIG_GLB_RELATIVE_PATH: &str = "../../test/browser/box-big.glb";

fn repo_path(relative: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(relative)
}

/// The checked-in Component core binary, read from the repository. The host
/// consumes it READ-ONLY; it is never copied, rebuilt, or modified.
pub fn component_bytes() -> Vec<u8> {
    std::fs::read(repo_path(COMPONENT_RELATIVE_PATH))
        .expect("checked-in GLB Component core binary must exist")
}

/// sha256 of the checked-in Component binary, hex-encoded. The L1 artifact-
/// identity pin: the native host must run the EXACT binary the browser tests.
pub fn component_hash() -> String {
    hex_sha256(&component_bytes())
}

pub fn box_glb_bytes() -> Vec<u8> {
    std::fs::read(repo_path(BOX_GLB_RELATIVE_PATH)).expect("checked-in box.glb must exist")
}

pub fn box_big_glb_bytes() -> Vec<u8> {
    std::fs::read(repo_path(BOX_BIG_GLB_RELATIVE_PATH)).expect("checked-in box-big.glb must exist")
}

/// sha256 of the small-box GLB fixture (per-instance-isolation discrimination
/// input). Pinned so a regenerated asset cannot silently shrink the
/// small-vs-big mesh-pixel gap that `per_instance_asset_isolation` relies on.
pub fn box_glb_hash() -> String {
    hex_sha256(&box_glb_bytes())
}

/// sha256 of the big-box GLB fixture (the discrimination's "different bytes").
pub fn box_big_glb_hash() -> String {
    hex_sha256(&box_big_glb_bytes())
}

fn hex_sha256(bytes: &[u8]) -> String {
    let digest = sha2::Sha256::digest(bytes);
    digest.iter().map(|b| format!("{b:02x}")).collect()
}

// ---------------------------------------------------------------------------
// Offscreen GfxWindow + MainThreadSpawner (no winit, no display)
// ---------------------------------------------------------------------------

/// A dummy offscreen "window". Only `width`/`height` are ever read: our custom
/// surface-webgpu never creates a wgpu Surface from the raw handles, so the
/// (required) raw-window-handle impls are simply unreachable.
/// Resizable: the Component creates its Surface with an EMPTY CreateDesc
/// (1x1), and the HOST sizes it afterward via `request_set_size` (exactly like
/// the browser adapter's `surface.setSize`). `Surface::width()/height()` read
/// the window live, so it must be mutable.
struct OffscreenWindow {
    size: Mutex<(u32, u32)>,
}

impl raw_window_handle::HasDisplayHandle for OffscreenWindow {
    fn display_handle(
        &self,
    ) -> Result<raw_window_handle::DisplayHandle<'_>, raw_window_handle::HandleError> {
        unreachable!("offscreen host never creates a wgpu surface from raw handles")
    }
}

impl raw_window_handle::HasWindowHandle for OffscreenWindow {
    fn window_handle(
        &self,
    ) -> Result<raw_window_handle::WindowHandle<'_>, raw_window_handle::HandleError> {
        unreachable!("offscreen host never creates a wgpu surface from raw handles")
    }
}

impl GfxWindow for OffscreenWindow {
    fn height(&self) -> u32 {
        self.size.lock().unwrap().1
    }
    fn width(&self) -> u32 {
        self.size.lock().unwrap().0
    }
    fn request_set_size(&self, width: Option<u32>, height: Option<u32>) {
        let mut size = self.size.lock().unwrap();
        if let Some(w) = width {
            size.0 = w;
        }
        if let Some(h) = height {
            size.1 = h;
        }
    }
}

/// Tracks the surfaces created for one workload so the driver can find the
/// Component's surface and send it animation frames.
type CreatedSurfaces = Arc<Mutex<Vec<Surface>>>;

/// No platform requires a main thread here (no winit, no real surface), so
/// "spawn on the main thread" runs the closure in place. `create_surface`
/// records each created Surface so the frame driver can reach it.
pub struct OffscreenSpawner {
    pub created: CreatedSurfaces,
}

impl MainThreadSpawner for OffscreenSpawner {
    fn spawn<F, T>(&self, f: F) -> impl Future<Output = T>
    where
        F: FnOnce() -> T + Send + 'static,
        T: Send + 'static,
    {
        std::future::ready(f())
    }

    fn create_surface(&self, desc: SurfaceDesc) -> Pin<Box<dyn Future<Output = Surface> + Send>> {
        let surface = Surface::new(Box::new(OffscreenWindow {
            size: Mutex::new((desc.width.unwrap_or(1), desc.height.unwrap_or(1))),
        }));
        self.created.lock().unwrap().push(surface.arc_clone());
        Box::pin(std::future::ready(surface))
    }
}

// ---------------------------------------------------------------------------
// Offscreen surface-webgpu Context
// ---------------------------------------------------------------------------

/// Host-owned offscreen render target: the WebGPU analogue of the browser
/// host's `TextureRenderTarget`. The texture is created in `configure` on the
/// Component's OWN device (a texture must be device-connected for the
/// Component to render into it). `present()` captures the BGRA frame.
pub struct OffscreenContext {
    /// The Surface this context renders for; its `width()/height()` are read
    /// LIVE each frame (the Component resizes it via request_set_size after
    /// the host sets the view size), so the per-frame color texture always
    /// matches the depth texture the Component rebuilds from the same source.
    surface: Surface,
    /// The Component's device resource rep + its wgpu-core id, captured in
    /// `configure` (both Copy, so present/get_current_texture can submit,
    /// readback and connect_texture without holding a borrow across the
    /// ResourceTable). The rep rebuilds the Resource handle on demand.
    device_rep: Option<u32>,
    device_id: Option<wgpu_core::id::DeviceId>,
    /// The format/usage captured in `configure`; textures are created fresh
    /// per frame in `get_current_texture`.
    format: wgpu_types::TextureFormat,
    usage: wgpu_types::TextureUsages,
    /// THIS frame's texture (created in `get_current_texture`, read in
    /// `present`; the Component destroys it after present, so it is per-frame).
    texture: Option<wgpu_core::id::TextureId>,
    /// Shared with the owning WorkloadState: every `present()` pushes one
    /// captured BGRA frame (padded rows, `bytes_per_row` stride).
    captured: Arc<Mutex<Vec<Vec<u8>>>>,
}

impl OffscreenContext {
    fn width(&self) -> u32 {
        self.surface.width().max(1)
    }
    fn height(&self) -> u32 {
        self.surface.height().max(1)
    }
    fn bytes_per_row_for(width: u32) -> u32 {
        // 256 = COPY_BYTES_PER_ROW_ALIGNMENT (and COPY_BUFFER_ALIGNMENT).
        width.div_ceil(64) * 256
    }
}

/// Ctx view handed to the generated surface-webgpu `add_to_linker`.
struct OffscreenSurfaceWebgpuCtx<'a> {
    table: &'a mut ResourceTable,
    instance: &'a Arc<wgpu_core::global::Global>,
    captured: &'a Arc<Mutex<Vec<Vec<u8>>>>,
    /// Set once the offscreen context is configured (the Component has its
    /// device and is ready to render) — the frame driver's readiness signal.
    ready: &'a Arc<Mutex<bool>>,
    /// The Component device's queue, captured in `configure` via the runtime's
    /// `HostGpuDevice::queue`; read by `present()`. `None` until configured.
    queue_id: &'a Arc<Mutex<Option<wgpu_core::id::QueueId>>>,
}

trait OffscreenSurfaceWebgpuCtxView: Send {
    fn offscreen_surface_webgpu_ctx(&mut self) -> OffscreenSurfaceWebgpuCtx<'_>;
}

struct HasOffscreenSurfaceWebgpu;

impl HasData for HasOffscreenSurfaceWebgpu {
    type Data<'a> = OffscreenSurfaceWebgpuCtx<'a>;
}

impl surface_webgpu::Host for OffscreenSurfaceWebgpuCtx<'_> {}

impl surface_webgpu::HostContext for OffscreenSurfaceWebgpuCtx<'_> {
    fn new(
        &mut self,
        surface: Resource<surface_webgpu::Surface>,
    ) -> wasmtime::Result<Resource<surface_webgpu::Context>> {
        let surface = self.table.get(&surface)?.arc_clone();
        Ok(self.table.push(OffscreenContext {
            surface,
            device_rep: None,
            device_id: None,
            format: wgpu_types::TextureFormat::Bgra8Unorm,
            usage: wgpu_types::TextureUsages::RENDER_ATTACHMENT
                | wgpu_types::TextureUsages::COPY_SRC,
            texture: None,
            captured: Arc::clone(self.captured),
        })?)
    }

    fn configure(
        &mut self,
        context: Resource<surface_webgpu::Context>,
        configuration: surface_webgpu::ContextConfiguration,
    ) -> wasmtime::Result<()> {
        // The Component-requested format is the host-preferred canvas format
        // (Bgra8unorm on Linux). OR in COPY_SRC so the frame can be copied out
        // — additive; the Component did not ask for it (same as the browser
        // TextureRenderTarget). Textures are created per-frame in
        // get_current_texture (a real surface hands out a fresh texture each
        // frame; the Component destroys its handle after present()).
        let format: wgpu_types::TextureFormat = configuration.format.into();
        let usage: wgpu_types::TextureUsages = configuration
            .usage
            .map(|u| u.try_into())
            .transpose()
            .map_err(|_| wasmtime::Error::msg("invalid gpu texture usage"))?
            .unwrap_or(wgpu_types::TextureUsages::RENDER_ATTACHMENT)
            | wgpu_types::TextureUsages::COPY_SRC;

        let device_rep = configuration.device.rep();
        let device_id = *self.table.get(&configuration.device)?.device_id();

        // Capture the Component device's QueueId so present() can submit the
        // readback copy. `Device.queue` is `pub(crate)`, but the runtime's
        // public `HostGpuDevice::queue` pushes that same `Arc<QueueId>` into
        // our table and returns its Resource — deref the Arc to the id, then
        // drop the extra resource (present() needs the id, not a table entry).
        let captured_queue = {
            use wasi_webgpu_wasmtime::wasi::webgpu::webgpu::HostGpuDevice;
            let mut webgpu_ctx = wasi_webgpu_wasmtime::WasiWebGpuCtx {
                instance: self.instance,
                table: self.table,
            };
            let queue_res = webgpu_ctx.queue(Resource::new_borrow(device_rep))?;
            let queue_id = **webgpu_ctx.table.get(&queue_res)?;
            webgpu_ctx.table.delete(queue_res)?;
            queue_id
        };
        *self.queue_id.lock().unwrap() = Some(captured_queue);

        let ctx = self.table.get_mut(&context)?;
        ctx.device_rep = Some(device_rep);
        ctx.device_id = Some(device_id);
        ctx.format = format;
        ctx.usage = usage;
        ctx.texture = None;
        *self.ready.lock().unwrap() = true;
        Ok(())
    }

    fn unconfigure(&mut self, context: Resource<surface_webgpu::Context>) -> wasmtime::Result<()> {
        let ctx = self.table.get_mut(&context)?;
        ctx.device_rep = None;
        ctx.texture = None;
        Ok(())
    }

    fn get_current_texture(
        &mut self,
        context: Resource<surface_webgpu::Context>,
    ) -> wasmtime::Result<Resource<surface_webgpu::GpuTexture>> {
        // A real surface acquires a FRESH texture per frame; the Component
        // drops its handle after present(), which DESTROYS the texture. So we
        // must hand out a new texture each call (recreating on the Component's
        // own device) rather than reuse one — otherwise frame 2 finds the
        // texture gone ("Texture does not exist"). Record it in the context so
        // present() reads THIS frame's texture.
        let (device_id, width, height, format, usage) = {
            let ctx = self.table.get(&context)?;
            let Some(device_id) = ctx.device_id else {
                wasmtime::bail!("offscreen context is not configured");
            };
            (device_id, ctx.width(), ctx.height(), ctx.format, ctx.usage)
        };
        let (texture_id, err) = self.instance.device_create_texture(
            device_id,
            &wgpu_types::TextureDescriptor {
                label: Some("lagrange-offscreen-target".into()),
                size: wgpu_types::Extent3d {
                    width,
                    height,
                    depth_or_array_layers: 1,
                },
                mip_level_count: 1,
                sample_count: 1,
                dimension: wgpu_types::TextureDimension::D2,
                format,
                usage,
                view_formats: vec![],
            },
            None,
        );
        if let Some(err) = err {
            wasmtime::bail!("offscreen device_create_texture failed: {err}");
        }
        // Record this frame's texture, then rebuild the device handle from its
        // rep to connect + push the GpuTexture resource.
        let device_rep = {
            let ctx = self.table.get_mut(&context)?;
            ctx.texture = Some(texture_id);
            ctx.device_rep.unwrap()
        };
        let device_res = Resource::<wasi_webgpu_wasmtime::Device>::new_borrow(device_rep);
        let texture = unsafe { self.table.get(&device_res)?.connect_texture(texture_id) };
        Ok(self.table.push(texture)?)
    }

    fn present(&mut self, context: Resource<surface_webgpu::Context>) -> wasmtime::Result<()> {
        // Take THIS frame's texture; the Component destroyed its handle, so
        // the texture is invalid after present and the next frame acquires a
        // fresh one in get_current_texture. Extract all fields, then drop the
        // borrow before re-borrowing the device immutably.
        let (device_id, texture_id, width, height, bytes_per_row, captured) = {
            let ctx = self.table.get_mut(&context)?;
            let (Some(device_id), Some(texture_id)) = (ctx.device_id, ctx.texture.take()) else {
                wasmtime::bail!("offscreen context is not configured");
            };
            (
                device_id,
                texture_id,
                ctx.width(),
                ctx.height(),
                OffscreenContext::bytes_per_row_for(ctx.width()),
                Arc::clone(&ctx.captured),
            )
        };
        // The Component's queue, captured in configure(). configure() always
        // runs before any present(), so this is Some on every present; if not,
        // fail loudly rather than capturing an all-zeros frame.
        let queue_id = (*self.queue_id.lock().unwrap())
            .ok_or_else(|| wasmtime::Error::msg("component queue not captured before present"))?;
        let size = bytes_per_row as u64 * height as u64;
        let instance = Arc::clone(self.instance);

        // Flush the Component's render submission (queue().submit() returns
        // immediately) BEFORE encoding our copy, so the texture holds the
        // rendered frame when we read it. Otherwise we can copy a texture the
        // GPU hasn't written yet (reads as all-zeros).
        instance
            .device_poll(device_id, wgpu_types::PollType::wait_indefinitely())
            .map_err(|e| wasmtime::Error::msg(format!("pre-copy device_poll: {e}")))?;

        // Readback buffer (host-side; the Component never sees it).
        let (buffer_id, err) = instance.device_create_buffer(
            device_id,
            &wgpu_types::BufferDescriptor {
                label: Some("lagrange-offscreen-readback".into()),
                size,
                usage: wgpu_types::BufferUsages::COPY_DST | wgpu_types::BufferUsages::MAP_READ,
                mapped_at_creation: false,
            },
            None,
        );
        if let Some(err) = err {
            wasmtime::bail!("offscreen device_create_buffer failed: {err}");
        }

        // Encode texture -> buffer copy.
        let (encoder_id, err) = instance.device_create_command_encoder(
            device_id,
            &wgpu_types::CommandEncoderDescriptor {
                label: Some("lagrange-offscreen-readback".into()),
            },
            None,
        );
        if let Some(err) = err {
            wasmtime::bail!("offscreen device_create_command_encoder failed: {err}");
        }
        instance
            .command_encoder_copy_texture_to_buffer(
                encoder_id,
                &wgpu_types::TexelCopyTextureInfo {
                    texture: texture_id,
                    mip_level: 0,
                    origin: wgpu_types::Origin3d::ZERO,
                    aspect: wgpu_types::TextureAspect::All,
                },
                &wgpu_types::TexelCopyBufferInfo {
                    buffer: buffer_id,
                    layout: wgpu_types::TexelCopyBufferLayout {
                        offset: 0,
                        bytes_per_row: Some(bytes_per_row),
                        rows_per_image: Some(height),
                    },
                },
                &wgpu_types::Extent3d {
                    width,
                    height,
                    depth_or_array_layers: 1,
                },
            )
            .map_err(|e| wasmtime::Error::msg(format!("copy_texture_to_buffer: {e}")))?;
        let (cmd_buffer_id, err) = instance.command_encoder_finish(
            encoder_id,
            &wgpu_types::CommandBufferDescriptor { label: None },
            None,
        );
        if let Some((label, err)) = err {
            wasmtime::bail!("offscreen command_encoder_finish failed ({label:?}): {err}");
        }

        // SUBMIT the copy on the Component's queue: an encoded command buffer
        // does not run until submitted (`buffer_map_async` does NOT execute
        // pending command buffers — the all-zeros bug). Then map + poll to
        // wait for the copy to land in the readback buffer.
        instance
            .queue_submit(queue_id, &[cmd_buffer_id])
            .map_err(|(_index, e)| wasmtime::Error::msg(format!("readback queue_submit: {e}")))?;
        instance
            .buffer_map_async(
                buffer_id,
                0,
                Some(size),
                wgpu_core::resource::BufferMapOperation {
                    host: wgpu_core::device::HostMap::Read,
                    callback: None,
                },
            )
            .map_err(|e| wasmtime::Error::msg(format!("buffer_map_async: {e}")))?;
        instance
            .poll_all_devices(true)
            .map_err(|e| wasmtime::Error::msg(format!("poll_all_devices: {e}")))?;
        instance
            .device_poll(device_id, wgpu_types::PollType::wait_indefinitely())
            .map_err(|e| wasmtime::Error::msg(format!("device_poll: {e}")))?;

        let (ptr, len) = instance
            .buffer_get_mapped_range(buffer_id, 0, Some(size))
            .map_err(|e| wasmtime::Error::msg(format!("buffer_get_mapped_range: {e}")))?;
        let frame = unsafe { std::slice::from_raw_parts(ptr.as_ptr(), len as usize) }.to_vec();
        instance
            .buffer_unmap(buffer_id)
            .map_err(|e| wasmtime::Error::msg(format!("buffer_unmap: {e}")))?;
        instance.buffer_destroy(buffer_id);

        captured.lock().unwrap().push(frame);
        Ok(())
    }

    fn drop(&mut self, context: Resource<surface_webgpu::Context>) -> wasmtime::Result<()> {
        self.table.delete(context)?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Per-instance workload state (one Store per instance => isolation)
// ---------------------------------------------------------------------------

struct WorkloadState {
    table: ResourceTable,
    instance: Arc<wgpu_core::global::Global>,
    spawner: OffscreenSpawner,
    /// This instance's attach-scoped asset allowlist (per-instance isolation:
    /// instance A's closure contains only A's bytes).
    allowlist: HashMap<String, Vec<u8>>,
    /// Frames captured by `present()` on this instance's offscreen context.
    captured: Arc<Mutex<Vec<Vec<u8>>>>,
    /// Set once the offscreen context is configured (frame-driver readiness).
    ready: Arc<Mutex<bool>>,
    /// What the Component printed (diagnostics).
    prints: Arc<Mutex<Vec<String>>>,
    /// The Component device's queue, captured in `configure`; read by `present()`.
    queue_id: Arc<Mutex<Option<wgpu_core::id::QueueId>>>,
}

impl HasData for WorkloadState {
    type Data<'a> = &'a mut WorkloadState;
}

impl WasiWebGpuCtxView for WorkloadState {
    fn webgpu_ctx(&mut self) -> WasiWebGpuCtx<'_> {
        WasiWebGpuCtx {
            instance: &self.instance,
            table: &mut self.table,
        }
    }
}

impl SurfaceCtxView for WorkloadState {
    type Spawner = OffscreenSpawner;
    fn surface_ctx(&mut self) -> SurfaceCtx<'_, OffscreenSpawner> {
        SurfaceCtx {
            table: &mut self.table,
            main_thread_spawner: &self.spawner,
        }
    }
}

impl OffscreenSurfaceWebgpuCtxView for WorkloadState {
    fn offscreen_surface_webgpu_ctx(&mut self) -> OffscreenSurfaceWebgpuCtx<'_> {
        OffscreenSurfaceWebgpuCtx {
            table: &mut self.table,
            instance: &self.instance,
            captured: &self.captured,
            ready: &self.ready,
            queue_id: &self.queue_id,
        }
    }
}

impl lagrange::assets::provider::Host for WorkloadState {
    fn load(&mut self, name: String) -> Result<Result<Vec<u8>, String>, wasmtime::Error> {
        Ok(match self.allowlist.get(&name) {
            Some(bytes) => Ok(bytes.clone()),
            None => Err(format!("not in allowlist: {name}")),
        })
    }
}

impl GlbRendererImports for WorkloadState {
    fn print(&mut self, s: String) -> wasmtime::Result<()> {
        self.prints.lock().unwrap().push(s.clone());
        log::info!(target: "glb-component", "{s}");
        Ok(())
    }
}

// Registration is per-interface via the marker-struct pattern (the runtime
// crates' design): each interface's generated `add_to_linker::<T, D>` routes
// to a HasData marker D whose `Data<'a>` is that interface's ctx struct, and
// WorkloadState's ctx views produce those ctx structs. The world's unified
// `GlbRenderer::add_to_linker` is NOT usable here because it requires a single
// D::Data that is simultaneously WasiWebGpuCtx + SurfaceCtx +
// OffscreenSurfaceWebgpuCtx (three different structs) — impossible. So we call
// each interface's add_to_linker with its own marker, then register the two
// world-owned imports (print + lagrange:assets/provider) against WorkloadState
// directly.

/// HasData marker for the lagrange:assets/provider + print imports, whose host
/// state is the WorkloadState itself.
struct HasWorkload;

impl HasData for HasWorkload {
    type Data<'a> = &'a mut WorkloadState;
}

// ---------------------------------------------------------------------------
// The host
// ---------------------------------------------------------------------------

/// One instance's run result: the frames its `present()` captured.
pub struct InstanceRun {
    /// One entry per presented frame: BGRA bytes, `bytes_per_row` stride
    /// (padded), `width`x`height` pixels.
    pub captured_frames: Vec<Vec<u8>>,
    pub width: u32,
    pub height: u32,
    pub bytes_per_row: u32,
    /// What the Component printed (diagnostics).
    pub prints: Vec<String>,
}

/// The native GLB host. One `Engine` + one shared wgpu `Global`; each
/// `run_instance`/`GlbInstance::spawn` gets its own `Store` (per-instance
/// isolation).
pub struct GlbHost {
    engine: Engine,
    instance: Arc<wgpu_core::global::Global>,
}

impl Default for GlbHost {
    fn default() -> Self {
        Self::new()
    }
}

impl GlbHost {
    pub fn new() -> Self {
        let mut config = Config::default();
        config.wasm_component_model(true);
        config.wasm_component_model_async(true);
        let engine = Engine::new(&config).expect("wasmtime engine");
        let instance = Arc::new(wgpu_core::global::Global::new(
            "webgpu",
            wgpu_types::InstanceDescriptor {
                backends: wgpu_types::Backends::all(),
                flags: wgpu_types::InstanceFlags::from_build_config(),
                backend_options: Default::default(),
                memory_budget_thresholds: Default::default(),
                display: None,
            },
            None,
        ));
        Self { engine, instance }
    }

    /// Run the checked-in Component once in a FRESH Store with the given
    /// attach-scoped asset allowlist, driving exactly `frames` animation
    /// frames, then return what `present()` captured.
    ///
    /// The Component's `start()` never resolves (it awaits frame events
    /// forever). If it TRAPS before the first frame is presented (e.g. a
    /// denied `load`), that error is surfaced here.
    ///
    /// Implemented in terms of `GlbInstance` (spawn -> drive N frames ->
    /// finish): the run-to-completion L1 API and the live-instance L3 API
    /// share one spawn/ready/size/frame-drive path.
    pub async fn run_instance(
        &self,
        allowlist: HashMap<String, Vec<u8>>,
        width: u32,
        height: u32,
        frames: usize,
    ) -> anyhow::Result<InstanceRun> {
        let instance = GlbInstance::spawn(self, allowlist, width, height).await?;
        instance.drive_frames(frames).await;
        instance.finish().await
    }

    /// Spawn the checked-in Component in a FRESH Store (attach-scoped asset
    /// allowlist, per-instance isolation), wait until it is READY (its
    /// offscreen surface-webgpu context configured + its wasi-gfx surface
    /// created), size the surface to the view, and return the LIVE instance
    /// held open across calls. This is the L3 live-instance seam the
    /// `LinuxRendererAdapter` holds behind a `glb` surface handle.
    async fn spawn_live(
        &self,
        allowlist: HashMap<String, Vec<u8>>,
        width: u32,
        height: u32,
    ) -> anyhow::Result<GlbInstance> {
        let component = wasmtime::component::Component::new(&self.engine, component_bytes())
            .map_err(|e| anyhow::anyhow!("compiling checked-in Component: {e}"))?;

        let mut linker: wasmtime::component::Linker<WorkloadState> =
            wasmtime::component::Linker::new(&self.engine);
        // Real wasi:webgpu + surface (runtime crates), our offscreen
        // surface-webgpu, and the world-owned print + lagrange:assets imports.
        wasi_webgpu_wasmtime::add_to_linker(&mut linker)?;
        surface_wasmtime::add_surface_to_linker(&mut linker)?;
        surface_webgpu::add_to_linker::<_, HasOffscreenSurfaceWebgpu>(
            &mut linker,
            WorkloadState::offscreen_surface_webgpu_ctx,
        )?;
        lagrange::assets::provider::add_to_linker::<_, HasWorkload>(&mut linker, |x| x)?;
        GlbRenderer::add_to_linker_imports::<_, HasWorkload>(&mut linker, |x| x)?;

        let created: CreatedSurfaces = Arc::new(Mutex::new(Vec::new()));
        let state = WorkloadState {
            table: ResourceTable::new(),
            instance: Arc::clone(&self.instance),
            spawner: OffscreenSpawner {
                created: Arc::clone(&created),
            },
            allowlist,
            captured: Arc::new(Mutex::new(Vec::new())),
            ready: Arc::new(Mutex::new(false)),
            prints: Arc::new(Mutex::new(Vec::new())),
            queue_id: Arc::new(Mutex::new(None)),
        };
        let captured = Arc::clone(&state.captured);
        let ready = Arc::clone(&state.ready);
        let prints = Arc::clone(&state.prints);
        let mut store = Store::new(&self.engine, state);

        let glb = GlbRenderer::instantiate_async(&mut store, &component, &linker).await?;

        // The Component creates its surface + subscribes to on-frame inside
        // start(), which never resolves (it awaits frame events forever). Run
        // it as a cancellable background task; we drive frames from here.
        let start_task = tokio::spawn(async move {
            glb.func_start().call_async(store.as_context_mut(), ()).await
        });

        // Wait until the Component is READY: its offscreen surface-webgpu
        // context is configured (it has its device + render texture) and its
        // wasi-gfx surface exists. If start traps first (e.g. denied asset),
        // surface that error.
        let surface = loop {
            // Surface-first: configure (which sets `ready`) can run before the
            // surface resource is pushed to `created`, so check the surface
            // independently of the ready flag and don't gate on both at once.
            if let Some(surface) = created.lock().unwrap().last().map(Surface::arc_clone) {
                if *ready.lock().unwrap() {
                    break surface;
                }
            }
            if start_task.is_finished() {
                let outcome = start_task.await?;
                outcome.map_err(|e| {
                    anyhow::anyhow!("component start() trapped before it was ready: {e}")
                })?;
                anyhow::bail!("component start() returned without becoming ready");
            }
            tokio::task::yield_now().await;
        };

        // Size the surface to the requested view (the Component created it
        // 1x1; the host sizes it afterward, like the browser adapter's
        // surface.setSize). The Component reads surface.width()/height() live.
        surface.request_set_size(Some(width), Some(height));

        Ok(GlbInstance {
            start_task,
            surface,
            captured,
            prints,
            width,
            height,
        })
    }
}

/// A LIVE GLB Component instance held open across calls (the L3 seam the
/// `LinuxRendererAdapter` uses for a `glb` surface): spawn -> drive_frames(n)
/// on demand -> read_latest_frame() -> drop/finish. Refactored from
/// `run_instance`'s logic so the run-to-completion L1 API and the live L3 API
/// share one spawn/ready/size/frame-drive path. The instance's Store +
/// start-task live on the tokio runtime that called `spawn`; frames are driven
/// on demand from the same runtime.
pub struct GlbInstance {
    /// The never-resolving Component start() task (aborted on teardown).
    start_task: tokio::task::JoinHandle<Result<(), wasmtime::Error>>,
    /// The Component's wasi-gfx surface: animation_frame() drives a frame.
    surface: Surface,
    /// Every BGRA frame present() captured (bytes_per_row stride, padded).
    captured: Arc<Mutex<Vec<Vec<u8>>>>,
    /// What the Component printed (diagnostics).
    prints: Arc<Mutex<Vec<String>>>,
    width: u32,
    height: u32,
}

impl GlbInstance {
    /// Spawn a live instance (see `GlbHost::spawn_live`). Must be called from
    /// within a tokio runtime (it `tokio::spawn`s the Component start task).
    pub async fn spawn(
        host: &GlbHost,
        allowlist: HashMap<String, Vec<u8>>,
        width: u32,
        height: u32,
    ) -> anyhow::Result<Self> {
        host.spawn_live(allowlist, width, height).await
    }

    /// Drive `n` animation frames, waiting after each for the Component to run
    /// its frame handler through present(). Stops early if the Component's
    /// start task finishes (e.g. it trapped).
    pub async fn drive_frames(&self, n: usize) {
        for _ in 0..n {
            self.surface.animation_frame();
            // Let the Component task run its frame handler through present().
            // A real timer sleep (not yield_now) so the tokio runtime actually
            // schedules the Component task's wakers and the wasmtime concurrent
            // stream machinery turns; yield_now can starve it.
            tokio::time::sleep(std::time::Duration::from_millis(30)).await;
            if self.start_task.is_finished() {
                break;
            }
        }
    }

    /// Drive animation frames until the Component presents at least one frame
    /// (load-independent), or give up after `max_frames` attempts. Unlike
    /// `drive_frames` (a fixed count for L1's run-to-completion), this is for
    /// the LIVE path: under host CPU contention the Component's frame handler
    /// may not be scheduled within a fixed number of 30ms sleeps, so a fixed
    /// count can return before present() runs. Looping until a frame is
    /// captured makes the pump robust regardless of load. Returns the number
    /// of captured frames (>= 1 on success, 0 if the bound was hit / the
    /// Component finished without presenting).
    pub async fn drive_until_frame(&self, max_frames: usize) -> usize {
        for _ in 0..max_frames {
            if !self.captured.lock().unwrap().is_empty() {
                break;
            }
            if self.start_task.is_finished() {
                break;
            }
            self.surface.animation_frame();
            // A real timer sleep (not yield_now) so the tokio runtime actually
            // schedules the Component task's wakers through present().
            tokio::time::sleep(std::time::Duration::from_millis(30)).await;
        }
        self.captured.lock().unwrap().len()
    }

    /// Resize the live surface (the Component reads width/height live next
    /// frame). Host-side: updates the view size the surface reports.
    pub fn resize(&self, width: u32, height: u32) {
        self.surface.request_set_size(Some(width), Some(height));
    }

    /// The most recently captured BGRA frame (host-side inspection seam), or
    /// None if the Component has not presented yet.
    pub fn read_latest_frame(&self) -> Option<Vec<u8>> {
        self.captured.lock().unwrap().last().cloned()
    }

    /// `bytes_per_row` for this instance's frames (COPY_BYTES_PER_ROW_ALIGNMENT
    /// padded). Uses the LIVE surface size so a resize is reflected.
    pub fn bytes_per_row(&self) -> u32 {
        self.surface.width().max(1).div_ceil(64) * 256
    }

    pub fn width(&self) -> u32 {
        self.surface.width().max(1)
    }

    pub fn height(&self) -> u32 {
        self.surface.height().max(1)
    }

    /// The nominal width/height this instance was spawned with (the view size
    /// before any resize).
    pub fn nominal_size(&self) -> (u32, u32) {
        (self.width, self.height)
    }

    /// Abort the Component's start task (idempotent). Dropping a `JoinHandle`
    /// only DETACHES the task — the never-resolving Component would keep its
    /// Store + attach-scoped asset closure alive on the runtime. So teardown
    /// (detach/destroy in the adapter, or a dropped live instance) MUST abort
    /// explicitly; this is the real native-teardown guarantee.
    fn abort(&self) {
        self.start_task.abort();
    }

    /// Tear the instance down and return everything it captured (the L1
    /// run-to-completion shape). Surfaces a Component trap and the
    /// zero-frames/denied-asset diagnostic as errors, exactly like the
    /// original `run_instance`.
    pub async fn finish(self) -> anyhow::Result<InstanceRun> {
        // Move the start task out without running Drop (we handle it explicitly
        // below, surfacing a trap rather than blindly aborting). The other
        // fields are behind Arc/Copy, so they are read, not moved.
        let this = std::mem::ManuallyDrop::new(self);
        // SAFETY: start_task is read out exactly once; `this` is not dropped.
        let start_task = unsafe { std::ptr::read(&this.start_task) };
        let captured = Arc::clone(&this.captured);
        let prints = Arc::clone(&this.prints);
        let width = this.width;
        let height = this.height;

        // If the Component's start trapped (e.g. denied asset), surface that
        // error rather than returning an empty capture as if it rendered.
        if start_task.is_finished() {
            let outcome = start_task.await?;
            if let Err(e) = outcome {
                return Err(anyhow::anyhow!("component start() trapped: {e}"));
            }
        } else {
            start_task.abort();
        }

        let captured_frames = std::mem::take(&mut *captured.lock().unwrap());
        let prints = std::mem::take(&mut *prints.lock().unwrap());

        // A run that presented ZERO frames did not render. The Component
        // reports a denied/failed asset load by printing (e.g. "not in
        // allowlist") and returning from start() WITHOUT trapping, so a trap
        // is not the only failure shape: surface the Component's own
        // diagnostics as the error instead of returning an empty capture.
        if captured_frames.is_empty() {
            anyhow::bail!(
                "component rendered no frames (diagnostics: {})",
                prints.join("; ")
            );
        }

        Ok(InstanceRun {
            captured_frames,
            width,
            height,
            bytes_per_row: width.div_ceil(64) * 256,
            prints,
        })
    }
}

impl Drop for GlbInstance {
    fn drop(&mut self) {
        // A dropped live instance (detach/destroy in the adapter) MUST abort
        // its Component start task: dropping the JoinHandle alone would detach
        // it and leak the Store + asset closure on the runtime.
        self.abort();
    }
}

// ---------------------------------------------------------------------------
// Mesh-pixel predicate (ported from test/browser/glb-proof.test.js, BGRA)
// ---------------------------------------------------------------------------

/// Count shaded-mesh pixels in a captured BGRA frame. Browser logic (RGBA):
/// `r > 40 && g > 35 && b < r - 15`. On Linux the frame is BGRA, so byte 0 is
/// B and byte 2 is R — expressed with explicit names so the swap is obvious.
pub fn mesh_pixels(frame: &[u8], width: u32, height: u32, bytes_per_row: u32) -> usize {
    let mut mesh = 0;
    for y in 0..height as usize {
        for x in 0..width as usize {
            let i = y * bytes_per_row as usize + x * 4;
            let b = frame[i] as i32;
            let g = frame[i + 1] as i32;
            let r = frame[i + 2] as i32;
            if r > 40 && g > 35 && b < r - 15 {
                mesh += 1;
            }
        }
    }
    mesh
}

#[cfg(test)]
mod send_sync_checks {
    use super::*;
    fn _assert_send<T: Send>() {}
    fn _glb_instance_send() {
        _assert_send::<GlbInstance>();
    }
}
