import {createBrowserRendererAdapter} from '../../src/browser-renderer/browser-renderer-adapter.js';
import {takeConstructedSince, constructedSurfaces} from '../../src/browser-renderer/surface.js';
import {TextureRenderTarget} from '../../src/browser-renderer/render-target.js';
import * as lagrangeWebgpu from '../../src/browser-renderer/webgpu.js';
import * as lagrangeSurface from '../../src/browser-renderer/surface.js';
import * as lagrangeSurfaceWebgpu from '../../src/browser-renderer/surface-webgpu.js';
import lagrangePrint from '../../src/browser-renderer/print.js';
import {start as startTriangle} from './components/triangle.component.js';
import {instantiate as instantiateGlb} from './components/glb/glb.component.js';

// The PR B browser proof harness. Drives the BrowserRendererAdapter through
// the full lifecycle against real Chrome WebGPU with the triangle Component.
// Exposes window.__lagrangeProof; each step returns data the driver asserts on.
//
// Two render-target realizations are exercised through the SAME Component and
// the SAME WIT/shim path — the Component is unaware which it got:
//   - texture mode: each Surface renders into a host-owned GPUTexture
//     (TextureRenderTarget). Deterministic CPU read-back; runs under
//     Xvfb/headless SwiftShader. This is the CI pixel proof.
//   - canvas mode (default): each Surface renders to its on-screen <canvas>
//     (CanvasRenderTarget). Real browser presentation; pixel read-back is
//     environment-dependent, so the automated assertions here cover the
//     multi-view/resize/teardown lifecycle, not pixels.
//
// The mode is chosen by the harness (host wiring), NOT by the Component,
// Presentation, or Compositor.

// One loadComponent factory per Session, for a given Component module. The
// Component constructs its Surface asynchronously inside start(); we kick
// start() off, then wait for the Surface it constructs so the adapter can size
// + mount its canvas. The construction registry is pruned on Surface.destroy().
function makeLoadComponent(startFn) {
  return async () => {
    const before = constructedSurfaces().length;
    const startPromise = startFn();
    let surface = null;
    for (let i = 0; i < 100 && !surface; i += 1) {
      await new Promise((resolve) => setTimeout(resolve, 10));
      const created = takeConstructedSince(before);
      surface = created[created.length - 1] ?? null;
    }
    return {start: () => startPromise, surface};
  };
}

// getCoreModule for the GLB Component's instantiation-mode transpile: fetch +
// compile each core wasm next to the Component module, cached by name.
const glbCoreModules = new Map();
function glbCoreModule(name) {
  if (!glbCoreModules.has(name)) {
    glbCoreModules.set(name, WebAssembly.compileStreaming(fetch(new URL(`./components/glb/${name}`, import.meta.url))));
  }
  return glbCoreModules.get(name);
}

// loadComponent for the GLB Component in jco INSTANTIATION mode: build a FRESH
// Component instance per attach, with THIS attach's host imports — critically
// its own `lagrange-assets` provider (the adapter-supplied assetProvider for
// this attach). There is no shared/provider-global state: instance A's imports
// closure contains only A's allowlist, so it cannot read instance B's bytes.
function makeGlbLoadComponent() {
  return async ({assetProvider}) => {
    const before = constructedSurfaces().length;
    const component = await instantiateGlb(glbCoreModule, {
      'lagrange-assets': assetProvider,
      'lagrange-webgpu': lagrangeWebgpu,
      'lagrange-surface': lagrangeSurface,
      'lagrange-surface-webgpu': lagrangeSurfaceWebgpu,
      'lagrange-print': {default: lagrangePrint},
    });
    const startPromise = component.start();
    let surface = null;
    for (let i = 0; i < 100 && !surface; i += 1) {
      await new Promise((resolve) => setTimeout(resolve, 10));
      const created = takeConstructedSince(before);
      surface = created[created.length - 1] ?? null;
    }
    return {start: () => startPromise, surface};
  };
}

const mount = document.getElementById('mount');

// Fetch the checked-in Box.glb (generated by generate-box-glb.js) as the
// durable asset bytes for the GLB proof.
async function fetchBoxGlb() {
  const res = await fetch('./box.glb');
  if (!res.ok) throw new Error(`failed to fetch box.glb: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}
// The discriminating larger Box (per-instance asset-isolation proof).
async function fetchBigBoxGlb() {
  const res = await fetch('./box-big.glb');
  if (!res.ok) throw new Error(`failed to fetch box-big.glb: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

function makeAdapter({texture = false, glb = false, assets = null} = {}) {
  return createBrowserRendererAdapter({
    loadComponent: glb ? makeGlbLoadComponent() : makeLoadComponent(startTriangle),
    mount,
    ...(texture
      ? {createRenderTarget: ({width, height}) => new TextureRenderTarget(width, height)}
      : {}),
    ...(assets ? {resolveAssets: assets} : {}),
  });
}

async function openView(adapter, descriptor, width, height) {
  const handle = await adapter.createSurface({kind: 'webgpu-canvas', width, height});
  await adapter.attachPresentation(handle, descriptor);
  // Let several frames render.
  for (let i = 0; i < 20; i += 1) {
    await new Promise((resolve) => requestAnimationFrame(resolve));
  }
  return handle;
}

const openTriangle = (adapter, width, height) => openView(adapter, {kind: 'triangle'}, width, height);

window.__lagrangeProof = {
  canvases: () => Array.from(document.querySelectorAll('#mount canvas')),

  // --- Texture-target (CI pixel proof) session ---
  async openTextureSession() {
    const adapter = makeAdapter({texture: true});
    const open = (w, h) => openTriangle(adapter, w, h);
    return {
      adapter,
      open,
      openTwo: async () => ({a: await open(320, 200), b: await open(640, 400)}),
      readRendered: (h) => adapter.readRenderedPixels(h),
      resize: async (h, w, ht) => {
        await adapter.resize(h, {width: w, height: ht});
        for (let i = 0; i < 5; i += 1) await new Promise((r) => requestAnimationFrame(r));
      },
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
    };
  },

  // --- Canvas-target (production lifecycle) session ---
  async openCanvasSession() {
    const adapter = makeAdapter({texture: false});
    const open = (w, h) => openTriangle(adapter, w, h);
    return {
      adapter,
      open,
      openTwo: async () => ({a: await open(320, 200), b: await open(640, 400)}),
      readRendered: (h) => adapter.readRenderedPixels(h),
      resize: async (h, w, ht) => {
        await adapter.resize(h, {width: w, height: ht});
        for (let i = 0; i < 5; i += 1) await new Promise((r) => requestAnimationFrame(r));
      },
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
      recreateSession: async (w, h) => {
        await adapter.destroyAll();
        const fresh = makeAdapter({texture: false});
        return openTriangle(fresh, w, h);
      },
    };
  },

  // --- GLB (PR C) session: the GLB renderer Component rendering a Box.glb
  // whose durable bytes cross the host -> Component boundary via
  // lagrange:assets/provider, into a TextureRenderTarget (CI pixel proof). ---
  async openGlbSession() {
    const boxBytes = await fetchBoxGlb();
    // resolveAssets (ASYNC, authorized): the environment resolves the
    // presentation-local asset ref to durable bytes for THIS attach. The
    // presentation-local name is 'main-model' — the Component calls
    // load('main-model') and never learns the underlying identity.
    const assets = async () => new Map([['main-model', boxBytes]]);
    let adapter = makeAdapter({texture: true, glb: true, assets});
    const open = (w, h) => openView(adapter, {kind: 'glb', asset: 'main-model'}, w, h);
    return {
      get adapter() { return adapter; },
      open,
      readRendered: (h) => adapter.readRenderedPixels(h),
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
      // A cold Session: destroy all (drops every instance + its provider
      // closure), then a FRESH adapter resolves + binds fresh bytes per attach.
      recreateSession: async (w, h) => {
        await adapter.destroyAll();
        adapter = makeAdapter({texture: true, glb: true, assets});
        return open(w, h);
      },
      // Negative proof: an attach whose allowlist lacks the asset must fail to
      // render (the instance's load('main-model') returns err).
      openMissingAsset: async (w, h) => {
        const emptyAssets = async () => new Map(); // empty allowlist
        const bad = makeAdapter({texture: true, glb: true, assets: emptyAssets});
        const handle = await bad.createSurface({kind: 'webgpu-canvas', width: w, height: h});
        await bad.attachPresentation(handle, {kind: 'glb', asset: 'missing'});
        for (let i = 0; i < 15; i += 1) await new Promise((r) => requestAnimationFrame(r));
        return {handle, adapter: bad};
      },
    };
  },

  // --- Per-instance asset ISOLATION proof (Bead 0dm): TWO simultaneous GLB
  // views, EACH loading 'main-model', but with DIFFERENT durable bytes (small
  // vs big Box). Each Component instance's import closure contains only its own
  // attach's allowlist, so A renders the small Box and B renders the big Box —
  // and A still renders the SMALL box AFTER B has been instantiated (the
  // critical falsifier against a shared/clobbered provider). ---
  async openTwoIsolatedGlbSessions(w, h) {
    const small = await fetchBoxGlb();
    const big = await fetchBigBoxGlb();
    // Two independent adapters/sessions, each resolving 'main-model' to its OWN
    // bytes. (A single renderer Session can also host two views; two Sessions
    // make the isolation claim strongest.)
    const assetsA = async () => new Map([['main-model', small]]);
    const assetsB = async () => new Map([['main-model', big]]);
    const adapterA = makeAdapter({texture: true, glb: true, assets: assetsA});
    const adapterB = makeAdapter({texture: true, glb: true, assets: assetsB});
    const openOn = async (adapter) => {
      const handle = await adapter.createSurface({kind: 'webgpu-canvas', width: w, height: h});
      await adapter.attachPresentation(handle, {kind: 'glb', asset: 'main-model'});
      for (let i = 0; i < 15; i += 1) await new Promise((r) => requestAnimationFrame(r));
      return handle;
    };
    const hA = await openOn(adapterA); // A first
    const frameA1 = await adapterA.readRenderedPixels(hA);
    const hB = await openOn(adapterB); // B instantiated AFTER A
    const frameB = await adapterB.readRenderedPixels(hB);
    // CRITICAL: read A AGAIN after B exists. A shared/clobbered provider would
    // now serve B's bytes to A; per-instance closures keep A on its own bytes.
    const frameA2 = await adapterA.readRenderedPixels(hA);
    return {
      frameA1, frameA2, frameB,
      destroy: async () => { await adapterA.destroyAll(); await adapterB.destroyAll(); },
    };
  },
};
