import {createBrowserRendererAdapter} from '../../src/browser-renderer/browser-renderer-adapter.js';
import {takeConstructedSince, constructedSurfaces} from '../../src/browser-renderer/surface.js';
import {TextureRenderTarget} from '../../src/browser-renderer/render-target.js';
import {start as startTriangle} from './components/triangle.component.js';
import {start as startGlb} from './components/glb/glb.component.js';

// The PR B browser proof harness. Drives the BrowserRendererAdapter through
// the full lifecycle against real Chrome WebGPU with the triangle Component.
// Exposes window.__lagrangeProof; each step returns data the driver asserts on.
//
// Two render-target realizations are exercised through the SAME Component and
// the SAME WIT/shim path — the Component is unaware which it got:
//   - texture mode: each Surface renders into a host-owned GPUTexture
//     (TextureRenderTarget). Deterministic CPU read-back; runs under
//     Xvfb/headless SwiftShader. This is the CI pixel proof.
//   - canvas mode (default): each Surface renders to its on-screen <canvas>
//     (CanvasRenderTarget). Real browser presentation; pixel read-back is
//     environment-dependent, so the automated assertions here cover the
//     multi-view/resize/teardown lifecycle, not pixels.
//
// The mode is chosen by the harness (host wiring), NOT by the Component,
// Presentation, or Compositor.

// One loadComponent factory per Session, for a given Component module. The
// Component constructs its Surface asynchronously inside start(); we kick
// start() off, then wait for the Surface it constructs so the adapter can size
// + mount its canvas. The construction registry is pruned on Surface.destroy().
function makeLoadComponent(startFn) {
  return async () => {
    const before = constructedSurfaces().length;
    const startPromise = startFn();
    let surface = null;
    for (let i = 0; i < 100 && !surface; i += 1) {
      await new Promise((resolve) => setTimeout(resolve, 10));
      const created = takeConstructedSince(before);
      surface = created[created.length - 1] ?? null;
    }
    return {start: () => startPromise, surface};
  };
}

const mount = document.getElementById('mount');

// Fetch the checked-in Box.glb (generated by generate-box-glb.js) as the
// durable asset bytes for the GLB proof.
async function fetchBoxGlb() {
  const res = await fetch('./box.glb');
  if (!res.ok) throw new Error(`failed to fetch box.glb: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

function makeAdapter({texture = false, startFn = startTriangle, assets = null} = {}) {
  return createBrowserRendererAdapter({
    loadComponent: makeLoadComponent(startFn),
    mount,
    ...(texture
      ? {createRenderTarget: ({width, height}) => new TextureRenderTarget(width, height)}
      : {}),
    ...(assets ? {resolveAssets: assets} : {}),
  });
}

async function openView(adapter, descriptor, width, height) {
  const handle = await adapter.createSurface({kind: 'webgpu-canvas', width, height});
  await adapter.attachPresentation(handle, descriptor);
  // Let several frames render.
  for (let i = 0; i < 20; i += 1) {
    await new Promise((resolve) => requestAnimationFrame(resolve));
  }
  return handle;
}

const openTriangle = (adapter, width, height) => openView(adapter, {kind: 'triangle'}, width, height);

window.__lagrangeProof = {
  canvases: () => Array.from(document.querySelectorAll('#mount canvas')),

  // --- Texture-target (CI pixel proof) session ---
  async openTextureSession() {
    const adapter = makeAdapter({texture: true});
    const open = (w, h) => openTriangle(adapter, w, h);
    return {
      adapter,
      open,
      openTwo: async () => ({a: await open(320, 200), b: await open(640, 400)}),
      readRendered: (h) => adapter.readRenderedPixels(h),
      resize: async (h, w, ht) => {
        await adapter.resize(h, {width: w, height: ht});
        for (let i = 0; i < 5; i += 1) await new Promise((r) => requestAnimationFrame(r));
      },
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
    };
  },

  // --- Canvas-target (production lifecycle) session ---
  async openCanvasSession() {
    const adapter = makeAdapter({texture: false});
    const open = (w, h) => openTriangle(adapter, w, h);
    return {
      adapter,
      open,
      openTwo: async () => ({a: await open(320, 200), b: await open(640, 400)}),
      readRendered: (h) => adapter.readRenderedPixels(h),
      resize: async (h, w, ht) => {
        await adapter.resize(h, {width: w, height: ht});
        for (let i = 0; i < 5; i += 1) await new Promise((r) => requestAnimationFrame(r));
      },
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
      recreateSession: async (w, h) => {
        await adapter.destroyAll();
        const fresh = makeAdapter({texture: false});
        return openTriangle(fresh, w, h);
      },
    };
  },

  // --- GLB (PR C) session: the GLB renderer Component rendering a Box.glb
  // whose durable bytes cross the host -> Component boundary via
  // lagrange:assets/provider, into a TextureRenderTarget (CI pixel proof). ---
  async openGlbSession() {
    const boxBytes = await fetchBoxGlb();
    // resolveAssets: the durable byte source for THIS attach. The adapter
    // injects it per-attach; a cold Session re-receives it.
    const assets = () => new Map([['box', boxBytes]]);
    let adapter = makeAdapter({texture: true, startFn: startGlb, assets});
    const open = (w, h) => openView(adapter, {kind: 'glb', asset: 'box'}, w, h);
    return {
      get adapter() { return adapter; },
      open,
      readRendered: (h) => adapter.readRenderedPixels(h),
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
      // A cold Session: destroy all (clears the asset source), then a FRESH
      // adapter re-injects the bytes on the next attach. The returned handle
      // belongs to the new adapter; readRendered is rebound to it.
      recreateSession: async (w, h) => {
        await adapter.destroyAll();
        adapter = makeAdapter({texture: true, startFn: startGlb, assets});
        return open(w, h);
      },
      // Negative proof: an attach whose byte source lacks the asset must fail
      // to render (the Component's load-glb returns err).
      openMissingAsset: async (w, h) => {
        const emptyAssets = () => new Map(); // no 'box'
        const bad = makeAdapter({texture: true, startFn: startGlb, assets: emptyAssets});
        const handle = await bad.createSurface({kind: 'webgpu-canvas', width: w, height: h});
        await bad.attachPresentation(handle, {kind: 'glb', asset: 'missing'});
        for (let i = 0; i < 15; i += 1) await new Promise((r) => requestAnimationFrame(r));
        return {handle, adapter: bad};
      },
    };
  },
};
