import {createBrowserRendererAdapter} from '../../src/browser-renderer/browser-renderer-adapter.js';
import {takeConstructedSince, constructedSurfaces} from '../../src/browser-renderer/surface.js';
import {TextureRenderTarget} from '../../src/browser-renderer/render-target.js';
import * as lagrangeWebgpu from '../../src/browser-renderer/webgpu.js';
import * as lagrangeSurface from '../../src/browser-renderer/surface.js';
import * as lagrangeSurfaceWebgpu from '../../src/browser-renderer/surface-webgpu.js';
import lagrangePrint from '../../src/browser-renderer/print.js';
import {start as startTriangle} from './components/triangle.component.js';
import {instantiate as instantiateGlb} from './components/glb/glb.component.js';
import {createCompositor} from '../../src/compositor.js';
import {createSelectionModel} from '../../src/selection-model.js';
import {createEnvironmentShell} from '../../src/environment-shell.js';
import {renderSemanticUiToDom} from '../../src/browser-renderer/dom-realizer.js';
import {validateSemanticUi} from '../../src/semantic-ui.js';

// The PR B browser proof harness. Drives the BrowserRendererAdapter through
// the full lifecycle against real Chrome WebGPU with the triangle Component.
// Exposes window.__lagrangeProof; each step returns data the driver asserts on.
//
// Two render-target realizations are exercised through the SAME Component and
// the SAME WIT/shim path — the Component is unaware which it got:
//   - texture mode: each Surface renders into a host-owned GPUTexture
//     (TextureRenderTarget). Deterministic CPU read-back; runs under
//     Xvfb/headless SwiftShader. This is the CI pixel proof.
//   - canvas mode (default): each Surface renders to its on-screen <canvas>
//     (CanvasRenderTarget). Real browser presentation; pixel read-back is
//     environment-dependent, so the automated assertions here cover the
//     multi-view/resize/teardown lifecycle, not pixels.
//
// The mode is chosen by the harness (host wiring), NOT by the Component,
// Presentation, or Compositor.

// One loadComponent factory per Session, for a given Component module. The
// Component constructs its Surface asynchronously inside start(); we kick
// start() off, then wait for the Surface it constructs so the adapter can size
// + mount its canvas. The construction registry is pruned on Surface.destroy().
function makeLoadComponent(startFn) {
  return async () => {
    const before = constructedSurfaces().length;
    const startPromise = startFn();
    let surface = null;
    for (let i = 0; i < 100 && !surface; i += 1) {
      await new Promise((resolve) => setTimeout(resolve, 10));
      const created = takeConstructedSince(before);
      surface = created[created.length - 1] ?? null;
    }
    return {start: () => startPromise, surface};
  };
}

// getCoreModule for the GLB Component's instantiation-mode transpile: fetch +
// compile each core wasm next to the Component module, cached by name.
const glbCoreModules = new Map();
function glbCoreModule(name) {
  if (!glbCoreModules.has(name)) {
    glbCoreModules.set(name, WebAssembly.compileStreaming(fetch(new URL(`./components/glb/${name}`, import.meta.url))));
  }
  return glbCoreModules.get(name);
}

// loadComponent for the GLB Component in jco INSTANTIATION mode: build a FRESH
// Component instance per attach, with THIS attach's host imports — critically
// its own `lagrange-assets` provider (the adapter-supplied assetProvider for
// this attach). There is no shared/provider-global state: instance A's imports
// closure contains only A's allowlist, so it cannot read instance B's bytes.
function makeGlbLoadComponent() {
  return async ({assetProvider}) => {
    const before = constructedSurfaces().length;
    const component = await instantiateGlb(glbCoreModule, {
      'lagrange-assets': assetProvider,
      'lagrange-webgpu': lagrangeWebgpu,
      'lagrange-surface': lagrangeSurface,
      'lagrange-surface-webgpu': lagrangeSurfaceWebgpu,
      'lagrange-print': {default: lagrangePrint},
    });
    const startPromise = component.start();
    let surface = null;
    for (let i = 0; i < 100 && !surface; i += 1) {
      await new Promise((resolve) => setTimeout(resolve, 10));
      const created = takeConstructedSince(before);
      surface = created[created.length - 1] ?? null;
    }
    return {start: () => startPromise, surface};
  };
}

const mount = document.getElementById('mount');

// Fetch the checked-in Box.glb (generated by generate-box-glb.js) as the
// durable asset bytes for the GLB proof.
async function fetchBoxGlb() {
  const res = await fetch('./box.glb');
  if (!res.ok) throw new Error(`failed to fetch box.glb: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}
// The discriminating larger Box (per-instance asset-isolation proof).
async function fetchBigBoxGlb() {
  const res = await fetch('./box-big.glb');
  if (!res.ok) throw new Error(`failed to fetch box-big.glb: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

function makeAdapter({texture = false, glb = false, assets = null} = {}) {
  return createBrowserRendererAdapter({
    loadComponent: glb ? makeGlbLoadComponent() : makeLoadComponent(startTriangle),
    mount,
    ...(texture
      ? {createRenderTarget: ({width, height}) => new TextureRenderTarget(width, height)}
      : {}),
    ...(assets ? {resolveAssets: assets} : {}),
  });
}

async function openView(adapter, descriptor, width, height) {
  const handle = await adapter.createSurface({kind: 'webgpu-canvas', width, height});
  await adapter.attachPresentation(handle, descriptor);
  // Let several frames render.
  for (let i = 0; i < 20; i += 1) {
    await new Promise((resolve) => requestAnimationFrame(resolve));
  }
  return handle;
}

const openTriangle = (adapter, width, height) => openView(adapter, {kind: 'triangle'}, width, height);

window.__lagrangeProof = {
  canvases: () => Array.from(document.querySelectorAll('#mount canvas')),

  // --- DOM + Component COEXISTENCE proof (Bead 9vl): navigator + inspector
  // (DOM tool realizations) + a GLB Component view behind ONE adapter. An
  // optional sentinel realizer for kind 'navigator' proves the dispatch seam is
  // INJECTED, not a hard-coded kind switch. ---
  async openCoexistenceSession({sentinelNavigator = false} = {}) {
    const boxBytes = await fetchBoxGlb();
    const assets = async () => new Map([['main-model', boxBytes]]);
    // An optional sentinel DOM realizer for 'navigator': if the adapter honors
    // the INJECTED realizerFor (not a hard-coded switch), this sentinel is used
    // and its marker node appears; a hard-coded switch would ignore it.
    let sentinelUsed = false;
    const realizerFor = sentinelNavigator
      ? (descriptor) => {
        if (descriptor?.kind === 'navigator') {
          sentinelUsed = true;
          return {
            attach: async ({surfaceHandle, emitIntent}) => {
              const node = document.createElement('div');
              node.id = 'sentinel-navigator';
              node.textContent = 'SENTINEL-NAVIGATOR-REALIZED';
              mount.appendChild(node);
              return {
                kind: 'dom',
                start() {}, stop() {}, resize() {},
                readPixels: async () => null,
                dispose() { if (node.parentNode) node.parentNode.removeChild(node); },
                isRunning: () => true,
              };
            },
          };
        }
        return undefined; // fall through to the default for other kinds
      }
      : undefined;
    // The adapter's realizerFor: honor an injected mapping, else the default
    // (tool kinds -> DOM, others -> Component). When realizerFor returns
    // undefined for a non-sentinel kind, the adapter must still dispatch right.
    const adapter = createBrowserRendererAdapter({
      loadComponent: makeGlbLoadComponent(),
      mount,
      createRenderTarget: ({width, height}) => new TextureRenderTarget(width, height),
      resolveAssets: assets,
      ...(sentinelNavigator ? {realizerFor} : {}),
    });
    const open = async (descriptor, w, h) => {
      const handle = await adapter.createSurface({kind: 'webgpu-canvas', width: w, height: h});
      await adapter.attachPresentation(handle, descriptor);
      for (let i = 0; i < 15; i += 1) await new Promise((r) => requestAnimationFrame(r));
      return handle;
    };
    // The navigator + inspector descriptors (tool kinds -> DOM realization).
    const navigatorDescriptor = {
      kind: 'navigator',
      subject: {kind: 'ref', imageId: 'img', objectId: 'obj-root'},
      parameters: {
        fields: {'slot-title': {kind: 'text', value: 'Root'}},
        references: [{kind: 'ref', imageId: 'img', objectId: 'obj-b'}, {kind: 'ref', imageId: 'img', objectId: 'obj-c'}],
      },
    };
    const inspectorDescriptor = {
      kind: 'inspector',
      subject: {kind: 'ref', imageId: 'img', objectId: 'obj-root'},
      // slot-title is editable (writable); slot-count is a read-only scalar.
      parameters: {fields: {'slot-title': {kind: 'text', value: 'Root'}, 'slot-count': {kind: 'int', value: 17}}, writable: ['slot-title'], references: []},
    };
    const glbDescriptor = {kind: 'glb', asset: 'main-model'};
    const navHandle = await open(navigatorDescriptor, 200, 200);
    const inspHandle = await open(inspectorDescriptor, 200, 200);
    const glbHandle = await open(glbDescriptor, 320, 200);
    return {
      adapter, navHandle, inspHandle, glbHandle,
      sentinelUsed: () => sentinelUsed,
      readGlb: () => adapter.readRenderedPixels(glbHandle),
      toolRoots: () => Array.from(document.querySelectorAll('#mount .lagrange-tool')),
      referenceButtons: () => Array.from(document.querySelectorAll('#mount .lagrange-tool-references button')),
      // The PRODUCTION edit path: the real inspector <input> realized by the
      // adapter's DOM realizer, committing through the adapter's emitIntent seam.
      inspectorFieldInputs: () => Array.from(document.querySelectorAll('#mount .lagrange-tool-inspector .lagrange-tool-field-input')),
      onIntent: (fn) => adapter.onIntent(fn),
      destroyAll: () => adapter.destroyAll(),
    };
  },

  // --- The REAL navigator -> selection -> inspector loop driven through real
  // DOM (Bead 9vl): a real EnvironmentShell + Compositor + DOM realizations.
  // The navigator is stubbed (no substrate in the browser) but the shell, the
  // Compositor, the DOM realization, and the activate-item -> selection ->
  // inspector path are all REAL. ---
  async openDomLoopSession() {
    const ref = (objectId) => ({kind: 'ref', imageId: 'img', objectId});
    // A stubbed ObjectNavigator: navigate(ref) yields an inspector Presentation
    // with the ref's fields + references (root carries refs to B and C).
    const RECORDS = {
      'obj-root': {fields: {'slot-title': {kind: 'text', value: 'Root'}}, references: [ref('obj-b'), ref('obj-c')]},
      'obj-b': {fields: {'slot-title': {kind: 'text', value: 'B'}, 'slot-count': {kind: 'int', value: 17}}, writable: ['slot-title'], references: []},
      'obj-c': {fields: {'slot-title': {kind: 'text', value: 'C'}}, references: []},
    };
    const navigator = {
      async navigate(subject) {
        const rec = RECORDS[subject.objectId] ?? {fields: {}, references: []};
        return {presentations: [{kind: 'inspector', subject, context: {fields: rec.fields, writable: rec.writable ?? [], references: rec.references}}], commands: [], failures: []};
      },
    };
    const adapter = createBrowserRendererAdapter({
      loadComponent: makeGlbLoadComponent(),
      mount,
      createRenderTarget: ({width, height}) => new TextureRenderTarget(width, height),
      resolveAssets: async () => new Map(),
    });
    const compositor = createCompositor({rendererAdapter: adapter});
    const selectionModel = createSelectionModel();
    // writableSlots threaded so the shell injects parameters.writable into the
    // inspector descriptor (the S4a path) — making obj-b's title editable in DOM.
    const shell = createEnvironmentShell({navigator, selectionModel, compositor, writableSlots: ['slot-title']});
    await shell.openWorkspace(ref('obj-root'), {viewDescriptorFor: () => ({kind: 'webgpu-canvas', width: 200, height: 200})});
    // Wire the DOM activate-item intents to selection. The navigator view is
    // opened first, so its surface handle is browser-surface-0.
    shell.bindDomIntents({adapter, navigatorSurfaceHandle: 'browser-surface-0'});
    return {
      adapter, compositor, selectionModel, shell,
      navigatorButtons: () => Array.from(document.querySelectorAll('#mount .lagrange-tool-navigator .lagrange-tool-references button')),
      inspectorText: () => document.querySelector('#mount .lagrange-tool-inspector')?.textContent ?? '',
      inspectorFieldInputs: () => Array.from(document.querySelectorAll('#mount .lagrange-tool-inspector .lagrange-tool-field-input')),
      onIntent: (fn) => adapter.onIntent(fn),
      inspectorSubject: () => compositor.durableIntent().find((v) => v.viewId === 'inspector-view')?.presentationDescriptor.subject.objectId ?? null,
      selected: () => selectionModel.selectedSubject()?.objectId ?? null,
      focused: () => compositor.focusedView(),
      destroyAll: () => adapter.destroyAll(),
    };
  },

  // --- Texture-target (CI pixel proof) session ---
  async openTextureSession() {
    const adapter = makeAdapter({texture: true});
    const open = (w, h) => openTriangle(adapter, w, h);
    return {
      adapter,
      open,
      openTwo: async () => ({a: await open(320, 200), b: await open(640, 400)}),
      readRendered: (h) => adapter.readRenderedPixels(h),
      resize: async (h, w, ht) => {
        await adapter.resize(h, {width: w, height: ht});
        for (let i = 0; i < 5; i += 1) await new Promise((r) => requestAnimationFrame(r));
      },
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
    };
  },

  // --- Canvas-target (production lifecycle) session ---
  async openCanvasSession() {
    const adapter = makeAdapter({texture: false});
    const open = (w, h) => openTriangle(adapter, w, h);
    return {
      adapter,
      open,
      openTwo: async () => ({a: await open(320, 200), b: await open(640, 400)}),
      readRendered: (h) => adapter.readRenderedPixels(h),
      resize: async (h, w, ht) => {
        await adapter.resize(h, {width: w, height: ht});
        for (let i = 0; i < 5; i += 1) await new Promise((r) => requestAnimationFrame(r));
      },
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
      recreateSession: async (w, h) => {
        await adapter.destroyAll();
        const fresh = makeAdapter({texture: false});
        return openTriangle(fresh, w, h);
      },
    };
  },

  // --- GLB (PR C) session: the GLB renderer Component rendering a Box.glb
  // whose durable bytes cross the host -> Component boundary via
  // lagrange:assets/provider, into a TextureRenderTarget (CI pixel proof). ---
  async openGlbSession() {
    const boxBytes = await fetchBoxGlb();
    // resolveAssets (ASYNC, authorized): the environment resolves the
    // presentation-local asset ref to durable bytes for THIS attach. The
    // presentation-local name is 'main-model' — the Component calls
    // load('main-model') and never learns the underlying identity.
    const assets = async () => new Map([['main-model', boxBytes]]);
    let adapter = makeAdapter({texture: true, glb: true, assets});
    const open = (w, h) => openView(adapter, {kind: 'glb', asset: 'main-model'}, w, h);
    return {
      get adapter() { return adapter; },
      open,
      readRendered: (h) => adapter.readRenderedPixels(h),
      destroyView: (h) => adapter.destroySurface(h),
      destroyAll: () => adapter.destroyAll(),
      // A cold Session: destroy all (drops every instance + its provider
      // closure), then a FRESH adapter resolves + binds fresh bytes per attach.
      recreateSession: async (w, h) => {
        await adapter.destroyAll();
        adapter = makeAdapter({texture: true, glb: true, assets});
        return open(w, h);
      },
      // Negative proof: an attach whose allowlist lacks the asset must fail to
      // render (the instance's load('main-model') returns err).
      openMissingAsset: async (w, h) => {
        const emptyAssets = async () => new Map(); // empty allowlist
        const bad = makeAdapter({texture: true, glb: true, assets: emptyAssets});
        const handle = await bad.createSurface({kind: 'webgpu-canvas', width: w, height: h});
        await bad.attachPresentation(handle, {kind: 'glb', asset: 'missing'});
        for (let i = 0; i < 15; i += 1) await new Promise((r) => requestAnimationFrame(r));
        return {handle, adapter: bad};
      },
    };
  },

  // --- Per-instance asset ISOLATION proof (Bead 0dm): TWO simultaneous GLB
  // views, EACH loading 'main-model', but with DIFFERENT durable bytes (small
  // vs big Box). Each Component instance's import closure contains only its own
  // attach's allowlist, so A renders the small Box and B renders the big Box —
  // and A still renders the SMALL box AFTER B has been instantiated (the
  // critical falsifier against a shared/clobbered provider). ---
  async openTwoIsolatedGlbSessions(w, h) {
    const small = await fetchBoxGlb();
    const big = await fetchBigBoxGlb();
    // Two independent adapters/sessions, each resolving 'main-model' to its OWN
    // bytes. (A single renderer Session can also host two views; two Sessions
    // make the isolation claim strongest.)
    const assetsA = async () => new Map([['main-model', small]]);
    const assetsB = async () => new Map([['main-model', big]]);
    const adapterA = makeAdapter({texture: true, glb: true, assets: assetsA});
    const adapterB = makeAdapter({texture: true, glb: true, assets: assetsB});
    const openOn = async (adapter) => {
      const handle = await adapter.createSurface({kind: 'webgpu-canvas', width: w, height: h});
      await adapter.attachPresentation(handle, {kind: 'glb', asset: 'main-model'});
      for (let i = 0; i < 15; i += 1) await new Promise((r) => requestAnimationFrame(r));
      return handle;
    };
    const hA = await openOn(adapterA); // A first
    const frameA1 = await adapterA.readRenderedPixels(hA);
    const hB = await openOn(adapterB); // B instantiated AFTER A
    const frameB = await adapterB.readRenderedPixels(hB);
    // CRITICAL: read A AGAIN after B exists. A shared/clobbered provider would
    // now serve B's bytes to A; per-instance closures keep A on its own bytes.
    const frameA2 = await adapterA.readRenderedPixels(hA);
    return {
      frameA1, frameA2, frameB,
      destroy: async () => { await adapterA.destroyAll(); await adapterB.destroyAll(); },
    };
  },

  // --- L2 cross-host identity: drive the browser SemanticUi->DOM rendering
  // path from a CHECKED-IN FIXTURE (fetched by URL), the SAME bytes the Linux
  // GTK realizer consumes. Asserts the DOM structure + the activate-item intent
  // for a fixture. ---
  async renderSemanticUiFixture(fixtureUrl, kind) {
    const res = await fetch(fixtureUrl);
    if (!res.ok) throw new Error(`failed to fetch fixture ${fixtureUrl}: ${res.status}`);
    const doc = validateSemanticUi(await res.json());
    const mount = document.getElementById('mount');
    mount.innerHTML = '';
    const listeners = [];
    const listen = (el, type, fn) => { el.addEventListener(type, fn); listeners.push([el, type, fn]); };
    const intents = [];
    const root = renderSemanticUiToDom({
      doc, kind, surfaceHandle: 'fixture-surface',
      listen, onAction: (key) => intents.push({kind: 'activate-item', key}),
      onEdit: (key, text) => intents.push({kind: 'edit-field', key, text}),
    });
    mount.appendChild(root);
    return {
      html: root.innerHTML,
      text: root.textContent,
      heading: root.querySelector('h3')?.textContent ?? null,
      reason: root.querySelector('.lagrange-tool-reason')?.textContent ?? null,
      fields: Array.from(root.querySelectorAll('.lagrange-tool-fields dt')).map((d) => d.textContent),
      // A read-only field's <dd> text; an editable field's <input> value.
      fieldValues: Array.from(root.querySelectorAll('.lagrange-tool-fields dd')).map((d) => d.querySelector('input')?.value ?? d.textContent),
      fieldInputs: Array.from(root.querySelectorAll('.lagrange-tool-field-input')).map((i) => i.value),
      buttons: Array.from(root.querySelectorAll('.lagrange-tool-references button')).map((b) => b.textContent),
      clickButton: (i) => { root.querySelectorAll('.lagrange-tool-references button')[i]?.click(); },
      // Type into the i-th editable input and press Enter (commit).
      editField: (i, text) => {
        const input = root.querySelectorAll('.lagrange-tool-field-input')[i];
        if (!input) return;
        input.value = text;
        input.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', bubbles: true}));
      },
      takeIntents: () => intents.splice(0, intents.length),
      dispose: () => { for (const [el, t, f] of listeners) el.removeEventListener(t, f); root.remove(); },
    };
  },
};
